version: "3.9"
services:
  babymed-frontend:
    restart: always
    image: babymed/frontend:latest
    hostname: babymed-frontend
    container_name: babymed-frontend
    ports:
      - "3005:80"
    networks:
      - external-net
networks:
  external-net:
    external:
      name: external-net
