name: Pipeline

on:
  push:
    branches: [ "master" ]
jobs:
  build:
    name: BUILD
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
      - name: Checkout current branch (fast)
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: "Publish local 🏗"
        run: |
          cd deployment/ 
          bash build.sh

      - name: Publishing images ...
        run: |
          bash publish push -f babymed-frontend -t latest

  deploy:
    name: DEPLOY
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Copy repository contents via scp
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "./deployment/*"
          target: "frontend"

      - name: Install SSH key of timeweb
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker login -p ${{ secrets.DOCKER_PASSWORD }} -u ${{ secrets.DOCKER_USERNAME }}
            cd ~/fontend/deployment
            chmod +x ./publish
            bash run.sh
            docker restart nginx
